{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "61c7d14c-0090-41fa-9a26-e0b7c09a288b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# 1. Load the dataset\n",
    "# We point to the csv file generated by your harvester\n",
    "df = pd.read_csv(\"dataset.csv\")\n",
    "\n",
    "# 2. Check the data\n",
    "print(f\"📊 Total Requests Captured: {len(df)}\")\n",
    "print(\"\\n--- First 5 Log Entries ---\")\n",
    "display(df.head())\n",
    "\n",
    "# 3. Visualizing Attacks vs Normal\n",
    "# We count how many times each specific path was hit\n",
    "plt.figure(figsize=(12, 6))\n",
    "df['path'].value_counts().plot(kind='bar', color='teal')\n",
    "plt.title('Traffic Distribution by Endpoint')\n",
    "plt.xlabel('API Endpoint')\n",
    "plt.ylabel('Count')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.grid(axis='y', linestyle='--', alpha=0.7)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
